### ISSUE TITLE
Simple issue with the Instructions

### ISSUE THREAD

**Issue by AttackParent99** [Mabzak-Knight/NyanTranslate#1]
Just a little bug in your setup instructions:

The command: $ pip install -r requirements.txt
Results in an error, because the repo does not have a "requirements.text" file.

The actual filename is "requirement.text"

**Comment by Mabzak-Knight** [comment]
Thank you for pointing that out! I appreciate your keen observation. I've corrected the filename to "requirements.txt" now. Feel free to try the setup instructions again with the updated information. If you encounter any further issues or have additional feedback, please let me know. Thanks!
